### ISSUE TITLE
Cookies are not sent in requests to remotedev-server

### ISSUE THREAD

**Issue by jenschelkopf** [zalmoxisus/redux-remotedev#2]
Cookies are not being sent in requests to remotedev-server, which makes it difficult utilize cookie based authorization with this library.

This is happening because the fetch library doesn't send cookies by default. Callers have to set {credentials: 'same-origin'}: https://fetch.spec.whatwg.org/#concept-request-credentials-mode

**Comment by zalmoxisus** [comment]
Implemented in `redux-remotedev@0.3.0`. Probably we could make it configurable (to use `omit` or `include`) in case some one need this.

Thanks for the suggestions!
